// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: api/proto/catalog/v1/catalog.proto

package catalogv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CabinetImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Alt           string                 `protobuf:"bytes,3,opt,name=alt,proto3" json:"alt,omitempty"`
	SortOrder     int32                  `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CabinetImage) Reset() {
	*x = CabinetImage{}
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CabinetImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CabinetImage) ProtoMessage() {}

func (x *CabinetImage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CabinetImage.ProtoReflect.Descriptor instead.
func (*CabinetImage) Descriptor() ([]byte, []int) {
	return file_api_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *CabinetImage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CabinetImage) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CabinetImage) GetAlt() string {
	if x != nil {
		return x.Alt
	}
	return ""
}

func (x *CabinetImage) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type Cabinet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Display       string                 `protobuf:"bytes,5,opt,name=display,proto3" json:"display,omitempty"`
	Condition     string                 `protobuf:"bytes,6,opt,name=condition,proto3" json:"condition,omitempty"`
	Quantity      int32                  `protobuf:"varint,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         int64                  `protobuf:"varint,8,opt,name=price,proto3" json:"price,omitempty"`
	Manufacturer  string                 `protobuf:"bytes,9,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Year          string                 `protobuf:"bytes,10,opt,name=year,proto3" json:"year,omitempty"`
	Images        []*CabinetImage        `protobuf:"bytes,11,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cabinet) Reset() {
	*x = Cabinet{}
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cabinet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cabinet) ProtoMessage() {}

func (x *Cabinet) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cabinet.ProtoReflect.Descriptor instead.
func (*Cabinet) Descriptor() ([]byte, []int) {
	return file_api_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *Cabinet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Cabinet) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Cabinet) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Cabinet) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Cabinet) GetDisplay() string {
	if x != nil {
		return x.Display
	}
	return ""
}

func (x *Cabinet) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *Cabinet) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Cabinet) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Cabinet) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *Cabinet) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *Cabinet) GetImages() []*CabinetImage {
	if x != nil {
		return x.Images
	}
	return nil
}

type ListCabinetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCabinetsRequest) Reset() {
	*x = ListCabinetsRequest{}
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCabinetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCabinetsRequest) ProtoMessage() {}

func (x *ListCabinetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCabinetsRequest.ProtoReflect.Descriptor instead.
func (*ListCabinetsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{2}
}

type ListCabinetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cabinets      []*Cabinet             `protobuf:"bytes,1,rep,name=cabinets,proto3" json:"cabinets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCabinetsResponse) Reset() {
	*x = ListCabinetsResponse{}
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCabinetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCabinetsResponse) ProtoMessage() {}

func (x *ListCabinetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCabinetsResponse.ProtoReflect.Descriptor instead.
func (*ListCabinetsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *ListCabinetsResponse) GetCabinets() []*Cabinet {
	if x != nil {
		return x.Cabinets
	}
	return nil
}

type GetCabinetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCabinetRequest) Reset() {
	*x = GetCabinetRequest{}
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCabinetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCabinetRequest) ProtoMessage() {}

func (x *GetCabinetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCabinetRequest.ProtoReflect.Descriptor instead.
func (*GetCabinetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *GetCabinetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCabinetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cabinet       *Cabinet               `protobuf:"bytes,1,opt,name=cabinet,proto3" json:"cabinet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCabinetResponse) Reset() {
	*x = GetCabinetResponse{}
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCabinetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCabinetResponse) ProtoMessage() {}

func (x *GetCabinetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCabinetResponse.ProtoReflect.Descriptor instead.
func (*GetCabinetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *GetCabinetResponse) GetCabinet() *Cabinet {
	if x != nil {
		return x.Cabinet
	}
	return nil
}

type ReserveStockRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CabinetId      string                 `protobuf:"bytes,1,opt,name=cabinet_id,json=cabinetId,proto3" json:"cabinet_id,omitempty"`
	Quantity       int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReserveStockRequest) Reset() {
	*x = ReserveStockRequest{}
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveStockRequest) ProtoMessage() {}

func (x *ReserveStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveStockRequest.ProtoReflect.Descriptor instead.
func (*ReserveStockRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *ReserveStockRequest) GetCabinetId() string {
	if x != nil {
		return x.CabinetId
	}
	return ""
}

func (x *ReserveStockRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ReserveStockRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type ReserveStockResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Cabinet        *Cabinet               `protobuf:"bytes,1,opt,name=cabinet,proto3" json:"cabinet,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReserveStockResponse) Reset() {
	*x = ReserveStockResponse{}
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveStockResponse) ProtoMessage() {}

func (x *ReserveStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveStockResponse.ProtoReflect.Descriptor instead.
func (*ReserveStockResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *ReserveStockResponse) GetCabinet() *Cabinet {
	if x != nil {
		return x.Cabinet
	}
	return nil
}

func (x *ReserveStockResponse) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

var File_api_proto_catalog_v1_catalog_proto protoreflect.FileDescriptor

const file_api_proto_catalog_v1_catalog_proto_rawDesc = "" +
	"\n" +
	"\"api/proto/catalog/v1/catalog.proto\x12\n" +
	"catalog.v1\"a\n" +
	"\fCabinetImage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x10\n" +
	"\x03alt\x18\x03 \x01(\tR\x03alt\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\x05R\tsortOrder\"\xab\x02\n" +
	"\aCabinet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x18\n" +
	"\adisplay\x18\x05 \x01(\tR\adisplay\x12\x1c\n" +
	"\tcondition\x18\x06 \x01(\tR\tcondition\x12\x1a\n" +
	"\bquantity\x18\a \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\b \x01(\x03R\x05price\x12\"\n" +
	"\fmanufacturer\x18\t \x01(\tR\fmanufacturer\x12\x12\n" +
	"\x04year\x18\n" +
	" \x01(\tR\x04year\x120\n" +
	"\x06images\x18\v \x03(\v2\x18.catalog.v1.CabinetImageR\x06images\"\x15\n" +
	"\x13ListCabinetsRequest\"G\n" +
	"\x14ListCabinetsResponse\x12/\n" +
	"\bcabinets\x18\x01 \x03(\v2\x13.catalog.v1.CabinetR\bcabinets\"#\n" +
	"\x11GetCabinetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x12GetCabinetResponse\x12-\n" +
	"\acabinet\x18\x01 \x01(\v2\x13.catalog.v1.CabinetR\acabinet\"y\n" +
	"\x13ReserveStockRequest\x12\x1d\n" +
	"\n" +
	"cabinet_id\x18\x01 \x01(\tR\tcabinetId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\"n\n" +
	"\x14ReserveStockResponse\x12-\n" +
	"\acabinet\x18\x01 \x01(\v2\x13.catalog.v1.CabinetR\acabinet\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey2\x83\x02\n" +
	"\x0eCatalogService\x12Q\n" +
	"\fListCabinets\x12\x1f.catalog.v1.ListCabinetsRequest\x1a .catalog.v1.ListCabinetsResponse\x12K\n" +
	"\n" +
	"GetCabinet\x12\x1d.catalog.v1.GetCabinetRequest\x1a\x1e.catalog.v1.GetCabinetResponse\x12Q\n" +
	"\fReserveStock\x12\x1f.catalog.v1.ReserveStockRequest\x1a .catalog.v1.ReserveStockResponseBFZDgithub.com/mateusfmfm/go-arcade-vault/api/proto/catalog/v1;catalogv1b\x06proto3"

var (
	file_api_proto_catalog_v1_catalog_proto_rawDescOnce sync.Once
	file_api_proto_catalog_v1_catalog_proto_rawDescData []byte
)

func file_api_proto_catalog_v1_catalog_proto_rawDescGZIP() []byte {
	file_api_proto_catalog_v1_catalog_proto_rawDescOnce.Do(func() {
		file_api_proto_catalog_v1_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_catalog_v1_catalog_proto_rawDesc), len(file_api_proto_catalog_v1_catalog_proto_rawDesc)))
	})
	return file_api_proto_catalog_v1_catalog_proto_rawDescData
}

var file_api_proto_catalog_v1_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_proto_catalog_v1_catalog_proto_goTypes = []any{
	(*CabinetImage)(nil),         // 0: catalog.v1.CabinetImage
	(*Cabinet)(nil),              // 1: catalog.v1.Cabinet
	(*ListCabinetsRequest)(nil),  // 2: catalog.v1.ListCabinetsRequest
	(*ListCabinetsResponse)(nil), // 3: catalog.v1.ListCabinetsResponse
	(*GetCabinetRequest)(nil),    // 4: catalog.v1.GetCabinetRequest
	(*GetCabinetResponse)(nil),   // 5: catalog.v1.GetCabinetResponse
	(*ReserveStockRequest)(nil),  // 6: catalog.v1.ReserveStockRequest
	(*ReserveStockResponse)(nil), // 7: catalog.v1.ReserveStockResponse
}
var file_api_proto_catalog_v1_catalog_proto_depIdxs = []int32{
	0, // 0: catalog.v1.Cabinet.images:type_name -> catalog.v1.CabinetImage
	1, // 1: catalog.v1.ListCabinetsResponse.cabinets:type_name -> catalog.v1.Cabinet
	1, // 2: catalog.v1.GetCabinetResponse.cabinet:type_name -> catalog.v1.Cabinet
	1, // 3: catalog.v1.ReserveStockResponse.cabinet:type_name -> catalog.v1.Cabinet
	2, // 4: catalog.v1.CatalogService.ListCabinets:input_type -> catalog.v1.ListCabinetsRequest
	4, // 5: catalog.v1.CatalogService.GetCabinet:input_type -> catalog.v1.GetCabinetRequest
	6, // 6: catalog.v1.CatalogService.ReserveStock:input_type -> catalog.v1.ReserveStockRequest
	3, // 7: catalog.v1.CatalogService.ListCabinets:output_type -> catalog.v1.ListCabinetsResponse
	5, // 8: catalog.v1.CatalogService.GetCabinet:output_type -> catalog.v1.GetCabinetResponse
	7, // 9: catalog.v1.CatalogService.ReserveStock:output_type -> catalog.v1.ReserveStockResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_catalog_v1_catalog_proto_init() }
func file_api_proto_catalog_v1_catalog_proto_init() {
	if File_api_proto_catalog_v1_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_catalog_v1_catalog_proto_rawDesc), len(file_api_proto_catalog_v1_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_catalog_v1_catalog_proto_goTypes,
		DependencyIndexes: file_api_proto_catalog_v1_catalog_proto_depIdxs,
		MessageInfos:      file_api_proto_catalog_v1_catalog_proto_msgTypes,
	}.Build()
	File_api_proto_catalog_v1_catalog_proto = out.File
	file_api_proto_catalog_v1_catalog_proto_goTypes = nil
	file_api_proto_catalog_v1_catalog_proto_depIdxs = nil
}
