// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: api/proto/catalog/v1/catalog.proto

package catalogv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CabinetImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Alt           string                 `protobuf:"bytes,3,opt,name=alt,proto3" json:"alt,omitempty"`
	SortOrder     int32                  `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CabinetImage) Reset() {
	*x = CabinetImage{}
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CabinetImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CabinetImage) ProtoMessage() {}

func (x *CabinetImage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CabinetImage.ProtoReflect.Descriptor instead.
func (*CabinetImage) Descriptor() ([]byte, []int) {
	return file_api_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *CabinetImage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CabinetImage) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CabinetImage) GetAlt() string {
	if x != nil {
		return x.Alt
	}
	return ""
}

func (x *CabinetImage) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type Cabinet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Display       string                 `protobuf:"bytes,5,opt,name=display,proto3" json:"display,omitempty"`
	Condition     string                 `protobuf:"bytes,6,opt,name=condition,proto3" json:"condition,omitempty"`
	Quantity      int32                  `protobuf:"varint,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         int64                  `protobuf:"varint,8,opt,name=price,proto3" json:"price,omitempty"`
	Manufacturer  string                 `protobuf:"bytes,9,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Year          string                 `protobuf:"bytes,10,opt,name=year,proto3" json:"year,omitempty"`
	Images        []*CabinetImage        `protobuf:"bytes,11,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cabinet) Reset() {
	*x = Cabinet{}
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cabinet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cabinet) ProtoMessage() {}

func (x *Cabinet) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cabinet.ProtoReflect.Descriptor instead.
func (*Cabinet) Descriptor() ([]byte, []int) {
	return file_api_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *Cabinet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Cabinet) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Cabinet) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Cabinet) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Cabinet) GetDisplay() string {
	if x != nil {
		return x.Display
	}
	return ""
}

func (x *Cabinet) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *Cabinet) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Cabinet) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Cabinet) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *Cabinet) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *Cabinet) GetImages() []*CabinetImage {
	if x != nil {
		return x.Images
	}
	return nil
}

type ListCabinetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCabinetsRequest) Reset() {
	*x = ListCabinetsRequest{}
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCabinetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCabinetsRequest) ProtoMessage() {}

func (x *ListCabinetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCabinetsRequest.ProtoReflect.Descriptor instead.
func (*ListCabinetsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{2}
}

type ListCabinetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cabinets      []*Cabinet             `protobuf:"bytes,1,rep,name=cabinets,proto3" json:"cabinets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCabinetsResponse) Reset() {
	*x = ListCabinetsResponse{}
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCabinetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCabinetsResponse) ProtoMessage() {}

func (x *ListCabinetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCabinetsResponse.ProtoReflect.Descriptor instead.
func (*ListCabinetsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *ListCabinetsResponse) GetCabinets() []*Cabinet {
	if x != nil {
		return x.Cabinets
	}
	return nil
}

type GetCabinetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCabinetRequest) Reset() {
	*x = GetCabinetRequest{}
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCabinetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCabinetRequest) ProtoMessage() {}

func (x *GetCabinetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCabinetRequest.ProtoReflect.Descriptor instead.
func (*GetCabinetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *GetCabinetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCabinetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cabinet       *Cabinet               `protobuf:"bytes,1,opt,name=cabinet,proto3" json:"cabinet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCabinetResponse) Reset() {
	*x = GetCabinetResponse{}
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCabinetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCabinetResponse) ProtoMessage() {}

func (x *GetCabinetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCabinetResponse.ProtoReflect.Descriptor instead.
func (*GetCabinetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *GetCabinetResponse) GetCabinet() *Cabinet {
	if x != nil {
		return x.Cabinet
	}
	return nil
}

type ReserveStockRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CabinetId      string                 `protobuf:"bytes,1,opt,name=cabinet_id,json=cabinetId,proto3" json:"cabinet_id,omitempty"`
	Quantity       int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReserveStockRequest) Reset() {
	*x = ReserveStockRequest{}
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveStockRequest) ProtoMessage() {}

func (x *ReserveStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveStockRequest.ProtoReflect.Descriptor instead.
func (*ReserveStockRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *ReserveStockRequest) GetCabinetId() string {
	if x != nil {
		return x.CabinetId
	}
	return ""
}

func (x *ReserveStockRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ReserveStockRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type ReserveStockResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Cabinet        *Cabinet               `protobuf:"bytes,1,opt,name=cabinet,proto3" json:"cabinet,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReserveStockResponse) Reset() {
	*x = ReserveStockResponse{}
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveStockResponse) ProtoMessage() {}

func (x *ReserveStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveStockResponse.ProtoReflect.Descriptor instead.
func (*ReserveStockResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *ReserveStockResponse) GetCabinet() *Cabinet {
	if x != nil {
		return x.Cabinet
	}
	return nil
}

func (x *ReserveStockResponse) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type OrderItemInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CabinetId     string                 `protobuf:"bytes,1,opt,name=cabinet_id,json=cabinetId,proto3" json:"cabinet_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemInput) Reset() {
	*x = OrderItemInput{}
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemInput) ProtoMessage() {}

func (x *OrderItemInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemInput.ProtoReflect.Descriptor instead.
func (*OrderItemInput) Descriptor() ([]byte, []int) {
	return file_api_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *OrderItemInput) GetCabinetId() string {
	if x != nil {
		return x.CabinetId
	}
	return ""
}

func (x *OrderItemInput) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CreateOrderRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Items          []*OrderItemInput      `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{9}
}

func (x *CreateOrderRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CreateOrderRequest) GetItems() []*OrderItemInput {
	if x != nil {
		return x.Items
	}
	return nil
}

type OrderLine struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CabinetId      string                 `protobuf:"bytes,1,opt,name=cabinet_id,json=cabinetId,proto3" json:"cabinet_id,omitempty"`
	Quantity       int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPriceCents int64                  `protobuf:"varint,3,opt,name=unit_price_cents,json=unitPriceCents,proto3" json:"unit_price_cents,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrderLine) Reset() {
	*x = OrderLine{}
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderLine) ProtoMessage() {}

func (x *OrderLine) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderLine.ProtoReflect.Descriptor instead.
func (*OrderLine) Descriptor() ([]byte, []int) {
	return file_api_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{10}
}

func (x *OrderLine) GetCabinetId() string {
	if x != nil {
		return x.CabinetId
	}
	return ""
}

func (x *OrderLine) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderLine) GetUnitPriceCents() int64 {
	if x != nil {
		return x.UnitPriceCents
	}
	return 0
}

type Order struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // pending_payment | paid | cancelled | failed
	TotalCents     int64                  `protobuf:"varint,4,opt,name=total_cents,json=totalCents,proto3" json:"total_cents,omitempty"`
	Items          []*OrderLine           `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,6,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_api_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{11}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetTotalCents() int64 {
	if x != nil {
		return x.TotalCents
	}
	return 0
}

func (x *Order) GetItems() []*OrderLine {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{12}
}

func (x *CreateOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{13}
}

func (x *GetOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_catalog_v1_catalog_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_catalog_v1_catalog_proto_rawDescGZIP(), []int{14}
}

func (x *GetOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

var File_api_proto_catalog_v1_catalog_proto protoreflect.FileDescriptor

const file_api_proto_catalog_v1_catalog_proto_rawDesc = "" +
	"\n" +
	"\"api/proto/catalog/v1/catalog.proto\x12\n" +
	"catalog.v1\"a\n" +
	"\fCabinetImage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x10\n" +
	"\x03alt\x18\x03 \x01(\tR\x03alt\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\x05R\tsortOrder\"\xab\x02\n" +
	"\aCabinet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x18\n" +
	"\adisplay\x18\x05 \x01(\tR\adisplay\x12\x1c\n" +
	"\tcondition\x18\x06 \x01(\tR\tcondition\x12\x1a\n" +
	"\bquantity\x18\a \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\b \x01(\x03R\x05price\x12\"\n" +
	"\fmanufacturer\x18\t \x01(\tR\fmanufacturer\x12\x12\n" +
	"\x04year\x18\n" +
	" \x01(\tR\x04year\x120\n" +
	"\x06images\x18\v \x03(\v2\x18.catalog.v1.CabinetImageR\x06images\"\x15\n" +
	"\x13ListCabinetsRequest\"G\n" +
	"\x14ListCabinetsResponse\x12/\n" +
	"\bcabinets\x18\x01 \x03(\v2\x13.catalog.v1.CabinetR\bcabinets\"#\n" +
	"\x11GetCabinetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x12GetCabinetResponse\x12-\n" +
	"\acabinet\x18\x01 \x01(\v2\x13.catalog.v1.CabinetR\acabinet\"y\n" +
	"\x13ReserveStockRequest\x12\x1d\n" +
	"\n" +
	"cabinet_id\x18\x01 \x01(\tR\tcabinetId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\"n\n" +
	"\x14ReserveStockResponse\x12-\n" +
	"\acabinet\x18\x01 \x01(\v2\x13.catalog.v1.CabinetR\acabinet\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\"K\n" +
	"\x0eOrderItemInput\x12\x1d\n" +
	"\n" +
	"cabinet_id\x18\x01 \x01(\tR\tcabinetId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"o\n" +
	"\x12CreateOrderRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x120\n" +
	"\x05items\x18\x02 \x03(\v2\x1a.catalog.v1.OrderItemInputR\x05items\"p\n" +
	"\tOrderLine\x12\x1d\n" +
	"\n" +
	"cabinet_id\x18\x01 \x01(\tR\tcabinetId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12(\n" +
	"\x10unit_price_cents\x18\x03 \x01(\x03R\x0eunitPriceCents\"\xbf\x01\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1f\n" +
	"\vtotal_cents\x18\x04 \x01(\x03R\n" +
	"totalCents\x12+\n" +
	"\x05items\x18\x05 \x03(\v2\x15.catalog.v1.OrderLineR\x05items\x12'\n" +
	"\x0fidempotency_key\x18\x06 \x01(\tR\x0eidempotencyKey\">\n" +
	"\x13CreateOrderResponse\x12'\n" +
	"\x05order\x18\x01 \x01(\v2\x11.catalog.v1.OrderR\x05order\"!\n" +
	"\x0fGetOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\";\n" +
	"\x10GetOrderResponse\x12'\n" +
	"\x05order\x18\x01 \x01(\v2\x11.catalog.v1.OrderR\x05order2\x9a\x03\n" +
	"\x0eCatalogService\x12Q\n" +
	"\fListCabinets\x12\x1f.catalog.v1.ListCabinetsRequest\x1a .catalog.v1.ListCabinetsResponse\x12K\n" +
	"\n" +
	"GetCabinet\x12\x1d.catalog.v1.GetCabinetRequest\x1a\x1e.catalog.v1.GetCabinetResponse\x12Q\n" +
	"\fReserveStock\x12\x1f.catalog.v1.ReserveStockRequest\x1a .catalog.v1.ReserveStockResponse\x12N\n" +
	"\vCreateOrder\x12\x1e.catalog.v1.CreateOrderRequest\x1a\x1f.catalog.v1.CreateOrderResponse\x12E\n" +
	"\bGetOrder\x12\x1b.catalog.v1.GetOrderRequest\x1a\x1c.catalog.v1.GetOrderResponseBFZDgithub.com/mateusfmfm/go-arcade-vault/api/proto/catalog/v1;catalogv1b\x06proto3"

var (
	file_api_proto_catalog_v1_catalog_proto_rawDescOnce sync.Once
	file_api_proto_catalog_v1_catalog_proto_rawDescData []byte
)

func file_api_proto_catalog_v1_catalog_proto_rawDescGZIP() []byte {
	file_api_proto_catalog_v1_catalog_proto_rawDescOnce.Do(func() {
		file_api_proto_catalog_v1_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_catalog_v1_catalog_proto_rawDesc), len(file_api_proto_catalog_v1_catalog_proto_rawDesc)))
	})
	return file_api_proto_catalog_v1_catalog_proto_rawDescData
}

var file_api_proto_catalog_v1_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_proto_catalog_v1_catalog_proto_goTypes = []any{
	(*CabinetImage)(nil),         // 0: catalog.v1.CabinetImage
	(*Cabinet)(nil),              // 1: catalog.v1.Cabinet
	(*ListCabinetsRequest)(nil),  // 2: catalog.v1.ListCabinetsRequest
	(*ListCabinetsResponse)(nil), // 3: catalog.v1.ListCabinetsResponse
	(*GetCabinetRequest)(nil),    // 4: catalog.v1.GetCabinetRequest
	(*GetCabinetResponse)(nil),   // 5: catalog.v1.GetCabinetResponse
	(*ReserveStockRequest)(nil),  // 6: catalog.v1.ReserveStockRequest
	(*ReserveStockResponse)(nil), // 7: catalog.v1.ReserveStockResponse
	(*OrderItemInput)(nil),       // 8: catalog.v1.OrderItemInput
	(*CreateOrderRequest)(nil),   // 9: catalog.v1.CreateOrderRequest
	(*OrderLine)(nil),            // 10: catalog.v1.OrderLine
	(*Order)(nil),                // 11: catalog.v1.Order
	(*CreateOrderResponse)(nil),  // 12: catalog.v1.CreateOrderResponse
	(*GetOrderRequest)(nil),      // 13: catalog.v1.GetOrderRequest
	(*GetOrderResponse)(nil),     // 14: catalog.v1.GetOrderResponse
}
var file_api_proto_catalog_v1_catalog_proto_depIdxs = []int32{
	0,  // 0: catalog.v1.Cabinet.images:type_name -> catalog.v1.CabinetImage
	1,  // 1: catalog.v1.ListCabinetsResponse.cabinets:type_name -> catalog.v1.Cabinet
	1,  // 2: catalog.v1.GetCabinetResponse.cabinet:type_name -> catalog.v1.Cabinet
	1,  // 3: catalog.v1.ReserveStockResponse.cabinet:type_name -> catalog.v1.Cabinet
	8,  // 4: catalog.v1.CreateOrderRequest.items:type_name -> catalog.v1.OrderItemInput
	10, // 5: catalog.v1.Order.items:type_name -> catalog.v1.OrderLine
	11, // 6: catalog.v1.CreateOrderResponse.order:type_name -> catalog.v1.Order
	11, // 7: catalog.v1.GetOrderResponse.order:type_name -> catalog.v1.Order
	2,  // 8: catalog.v1.CatalogService.ListCabinets:input_type -> catalog.v1.ListCabinetsRequest
	4,  // 9: catalog.v1.CatalogService.GetCabinet:input_type -> catalog.v1.GetCabinetRequest
	6,  // 10: catalog.v1.CatalogService.ReserveStock:input_type -> catalog.v1.ReserveStockRequest
	9,  // 11: catalog.v1.CatalogService.CreateOrder:input_type -> catalog.v1.CreateOrderRequest
	13, // 12: catalog.v1.CatalogService.GetOrder:input_type -> catalog.v1.GetOrderRequest
	3,  // 13: catalog.v1.CatalogService.ListCabinets:output_type -> catalog.v1.ListCabinetsResponse
	5,  // 14: catalog.v1.CatalogService.GetCabinet:output_type -> catalog.v1.GetCabinetResponse
	7,  // 15: catalog.v1.CatalogService.ReserveStock:output_type -> catalog.v1.ReserveStockResponse
	12, // 16: catalog.v1.CatalogService.CreateOrder:output_type -> catalog.v1.CreateOrderResponse
	14, // 17: catalog.v1.CatalogService.GetOrder:output_type -> catalog.v1.GetOrderResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_proto_catalog_v1_catalog_proto_init() }
func file_api_proto_catalog_v1_catalog_proto_init() {
	if File_api_proto_catalog_v1_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_catalog_v1_catalog_proto_rawDesc), len(file_api_proto_catalog_v1_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_catalog_v1_catalog_proto_goTypes,
		DependencyIndexes: file_api_proto_catalog_v1_catalog_proto_depIdxs,
		MessageInfos:      file_api_proto_catalog_v1_catalog_proto_msgTypes,
	}.Build()
	File_api_proto_catalog_v1_catalog_proto = out.File
	file_api_proto_catalog_v1_catalog_proto_goTypes = nil
	file_api_proto_catalog_v1_catalog_proto_depIdxs = nil
}
