package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	catalogv1 "github.com/mateusfmfm/go-arcade-vault/api/proto/catalog/v1"
	"github.com/mateusfmfm/go-arcade-vault/internal/gateway/graph/model"
)

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input model.CreateOrderInput) (*model.Order, error) {

	items := make([]*catalogv1.OrderItemInput, 0, len(input.Items))
	for _, item := range input.Items {
		items = append(items, &catalogv1.OrderItemInput{
			CabinetId: item.CabinetID,
			Quantity:  int32(item.Quantity),
		})
	}
	resp, err := r.Catalog.CreateOrder(ctx, &catalogv1.CreateOrderRequest{IdempotencyKey: input.IdempotencyKey, Items: items})
	if err != nil {
		return nil, err
	}
	return mapOrder(resp.GetOrder()), nil
}

// Cabinets is the resolver for the cabinets field.
func (r *queryResolver) Cabinets(ctx context.Context) ([]*model.Cabinet, error) {
	resp, err := r.Catalog.ListCabinets(ctx, &catalogv1.ListCabinetsRequest{})
	if err != nil {
		return nil, err
	}
	cabinets := make([]*model.Cabinet, 0, len(resp.GetCabinets()))
	for _, c := range resp.GetCabinets() {
		cabinets = append(cabinets, mapCabinet(c))
	}
	return cabinets, nil
}

// Cabinet is the resolver for the cabinet field.
func (r *queryResolver) Cabinet(ctx context.Context, id string) (*model.Cabinet, error) {
	resp, err := r.Catalog.GetCabinet(ctx, &catalogv1.GetCabinetRequest{Id: id})
	if err != nil {
		return nil, err
	}
	return mapCabinet(resp.GetCabinet()), nil
}

func mapOrder(o *catalogv1.Order) *model.Order {
	if o == nil {
		return nil
	}
	items := make([]*model.OrderLine, 0, len(o.GetItems()))
	for _, item := range o.GetItems() {
		items = append(items, &model.OrderLine{
			CabinetID:      item.GetCabinetId(),
			Quantity:       int(item.GetQuantity()),
			UnitPriceCents: int(item.GetUnitPriceCents()),
		})
	}
	return &model.Order{
		ID:             o.GetId(),
		UserID:         o.GetUserId(),
		Status:         o.GetStatus(),
		TotalCents:     int(o.GetTotalCents()),
		IdempotencyKey: o.GetIdempotencyKey(),
		Items:          items,
	}
}

func mapCabinet(c *catalogv1.Cabinet) *model.Cabinet {
	if c == nil {
		return nil
	}
	images := make([]*model.CabinetImage, 0, len(c.GetImages()))
	for _, img := range c.GetImages() {
		images = append(images, &model.CabinetImage{
			ID:        img.GetId(),
			URL:       img.GetUrl(),
			Alt:       img.GetAlt(),
			SortOrder: int(img.GetSortOrder()),
		})
	}
	return &model.Cabinet{
		ID:           c.GetId(),
		Slug:         c.GetSlug(),
		Model:        c.GetModel(),
		Type:         c.GetType(),
		Display:      c.GetDisplay(),
		Condition:    c.GetCondition(),
		Quantity:     int(c.GetQuantity()),
		PriceCents:   int(c.GetPrice()),
		Manufacturer: c.GetManufacturer(),
		Year:         c.GetYear(),
		Images:       images,
	}
}

// Order is the resolver for the order field.
func (r *queryResolver) Order(ctx context.Context, id string) (*model.Order, error) {
	resp, err := r.Catalog.GetOrder(ctx, &catalogv1.GetOrderRequest{Id: id})
	if err != nil {
		return nil, err
	}
	return mapOrder(resp.GetOrder()), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
