// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Cabinet struct {
	ID           string          `json:"id"`
	Slug         string          `json:"slug"`
	Model        string          `json:"model"`
	Type         string          `json:"type"`
	Display      string          `json:"display"`
	Condition    string          `json:"condition"`
	Quantity     int             `json:"quantity"`
	PriceCents   int             `json:"priceCents"`
	Manufacturer string          `json:"manufacturer"`
	Year         string          `json:"year"`
	Images       []*CabinetImage `json:"images"`
}

type CabinetImage struct {
	ID        string `json:"id"`
	URL       string `json:"url"`
	Alt       string `json:"alt"`
	SortOrder int    `json:"sortOrder"`
}

type CreateOrderInput struct {
	IdempotencyKey string                  `json:"idempotencyKey"`
	Items          []*CreateOrderItemInput `json:"items"`
}

type CreateOrderItemInput struct {
	CabinetID string `json:"cabinetId"`
	Quantity  int    `json:"quantity"`
}

type Mutation struct {
}

type Order struct {
	ID             string       `json:"id"`
	UserID         string       `json:"userId"`
	Status         string       `json:"status"`
	TotalCents     int          `json:"totalCents"`
	IdempotencyKey string       `json:"idempotencyKey"`
	Items          []*OrderLine `json:"items"`
}

type OrderLine struct {
	CabinetID      string `json:"cabinetId"`
	Quantity       int    `json:"quantity"`
	UnitPriceCents int    `json:"unitPriceCents"`
}

type Query struct {
}
