// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cabinets.sql

package db

import (
	"context"
)

const createReservation = `-- name: CreateReservation :exec
INSERT INTO catalog.reservations (idempotency_key, cabinet_id, quantity)
VALUES ($1, $2, $3)
`

type CreateReservationParams struct {
	IdempotencyKey string `json:"idempotency_key"`
	CabinetID      string `json:"cabinet_id"`
	Quantity       int32  `json:"quantity"`
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) error {
	_, err := q.db.Exec(ctx, createReservation, arg.IdempotencyKey, arg.CabinetID, arg.Quantity)
	return err
}

const decrementStock = `-- name: DecrementStock :one
UPDATE catalog.cabinets
SET quantity = quantity - $1,
    updated_at = NOW()
WHERE id = $2 AND quantity >= $1
RETURNING id, slug, model, type, display, condition, quantity, price, manufacturer, year, created_at, updated_at
`

type DecrementStockParams struct {
	Quantity int32  `json:"quantity"`
	ID       string `json:"id"`
}

func (q *Queries) DecrementStock(ctx context.Context, arg DecrementStockParams) (CatalogCabinet, error) {
	row := q.db.QueryRow(ctx, decrementStock, arg.Quantity, arg.ID)
	var i CatalogCabinet
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Model,
		&i.Type,
		&i.Display,
		&i.Condition,
		&i.Quantity,
		&i.Price,
		&i.Manufacturer,
		&i.Year,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCabinet = `-- name: GetCabinet :one
SELECT id, slug, model, type, display, condition, quantity, price, manufacturer, year, created_at, updated_at FROM catalog.cabinets
WHERE id = $1
`

func (q *Queries) GetCabinet(ctx context.Context, id string) (CatalogCabinet, error) {
	row := q.db.QueryRow(ctx, getCabinet, id)
	var i CatalogCabinet
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Model,
		&i.Type,
		&i.Display,
		&i.Condition,
		&i.Quantity,
		&i.Price,
		&i.Manufacturer,
		&i.Year,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReservation = `-- name: GetReservation :one
SELECT idempotency_key, cabinet_id, quantity, created_at FROM catalog.reservations
WHERE idempotency_key = $1
`

func (q *Queries) GetReservation(ctx context.Context, idempotencyKey string) (CatalogReservation, error) {
	row := q.db.QueryRow(ctx, getReservation, idempotencyKey)
	var i CatalogReservation
	err := row.Scan(
		&i.IdempotencyKey,
		&i.CabinetID,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const listCabinets = `-- name: ListCabinets :many
SELECT id, slug, model, type, display, condition, quantity, price, manufacturer, year, created_at, updated_at FROM catalog.cabinets
ORDER BY created_at DESC
`

func (q *Queries) ListCabinets(ctx context.Context) ([]CatalogCabinet, error) {
	rows, err := q.db.Query(ctx, listCabinets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CatalogCabinet
	for rows.Next() {
		var i CatalogCabinet
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Model,
			&i.Type,
			&i.Display,
			&i.Condition,
			&i.Quantity,
			&i.Price,
			&i.Manufacturer,
			&i.Year,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
