// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cabinets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReservation = `-- name: CreateReservation :exec
INSERT INTO catalog.reservations (idempotency_key, cabinet_id, quantity)
VALUES ($1, $2, $3)
`

type CreateReservationParams struct {
	IdempotencyKey string `json:"idempotency_key"`
	CabinetID      string `json:"cabinet_id"`
	Quantity       int32  `json:"quantity"`
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) error {
	_, err := q.db.Exec(ctx, createReservation, arg.IdempotencyKey, arg.CabinetID, arg.Quantity)
	return err
}

const decrementStock = `-- name: DecrementStock :one
UPDATE catalog.cabinets c
SET quantity = quantity - $1,
    updated_at = NOW()
WHERE c.id = $2 AND c.quantity >= $1
RETURNING
    c.id,
    c.slug,
    c.model,
    c.type,
    c.display,
    c.condition,
    c.quantity,
    c.price,
    c.manufacturer,
    c.year,
    c.created_at,
    c.updated_at,
    COALESCE((
        SELECT json_agg(
            json_build_object(
                'id', i.id,
                'url', i.url,
                'alt', i.alt,
                'sort_order', i.sort_order
            )
            ORDER BY i.sort_order ASC, i.created_at ASC
        )
        FROM catalog.cabinet_images i
        WHERE i.cabinet_id = c.id
    ), '[]'::json)::jsonb AS images
`

type DecrementStockParams struct {
	Quantity int32  `json:"quantity"`
	ID       string `json:"id"`
}

type DecrementStockRow struct {
	ID           string             `json:"id"`
	Slug         string             `json:"slug"`
	Model        string             `json:"model"`
	Type         string             `json:"type"`
	Display      string             `json:"display"`
	Condition    string             `json:"condition"`
	Quantity     int32              `json:"quantity"`
	Price        int64              `json:"price"`
	Manufacturer string             `json:"manufacturer"`
	Year         string             `json:"year"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Images       CabinetImages      `json:"images"`
}

func (q *Queries) DecrementStock(ctx context.Context, arg DecrementStockParams) (DecrementStockRow, error) {
	row := q.db.QueryRow(ctx, decrementStock, arg.Quantity, arg.ID)
	var i DecrementStockRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Model,
		&i.Type,
		&i.Display,
		&i.Condition,
		&i.Quantity,
		&i.Price,
		&i.Manufacturer,
		&i.Year,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Images,
	)
	return i, err
}

const getCabinet = `-- name: GetCabinet :one
SELECT
    c.id,
    c.slug,
    c.model,
    c.type,
    c.display,
    c.condition,
    c.quantity,
    c.price,
    c.manufacturer,
    c.year,
    c.created_at,
    c.updated_at,
    COALESCE((
        SELECT json_agg(
            json_build_object(
                'id', i.id,
                'url', i.url,
                'alt', i.alt,
                'sort_order', i.sort_order
            )
            ORDER BY i.sort_order ASC, i.created_at ASC
        )
        FROM catalog.cabinet_images i
        WHERE i.cabinet_id = c.id
    ), '[]'::json)::jsonb AS images
FROM catalog.cabinets c
WHERE c.id = $1
`

type GetCabinetRow struct {
	ID           string             `json:"id"`
	Slug         string             `json:"slug"`
	Model        string             `json:"model"`
	Type         string             `json:"type"`
	Display      string             `json:"display"`
	Condition    string             `json:"condition"`
	Quantity     int32              `json:"quantity"`
	Price        int64              `json:"price"`
	Manufacturer string             `json:"manufacturer"`
	Year         string             `json:"year"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Images       CabinetImages      `json:"images"`
}

func (q *Queries) GetCabinet(ctx context.Context, id string) (GetCabinetRow, error) {
	row := q.db.QueryRow(ctx, getCabinet, id)
	var i GetCabinetRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Model,
		&i.Type,
		&i.Display,
		&i.Condition,
		&i.Quantity,
		&i.Price,
		&i.Manufacturer,
		&i.Year,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Images,
	)
	return i, err
}

const getReservation = `-- name: GetReservation :one
SELECT idempotency_key, cabinet_id, quantity, created_at FROM catalog.reservations
WHERE idempotency_key = $1
`

func (q *Queries) GetReservation(ctx context.Context, idempotencyKey string) (CatalogReservation, error) {
	row := q.db.QueryRow(ctx, getReservation, idempotencyKey)
	var i CatalogReservation
	err := row.Scan(
		&i.IdempotencyKey,
		&i.CabinetID,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const listCabinets = `-- name: ListCabinets :many
SELECT
    c.id,
    c.slug,
    c.model,
    c.type,
    c.display,
    c.condition,
    c.quantity,
    c.price,
    c.manufacturer,
    c.year,
    c.created_at,
    c.updated_at,
    COALESCE((
        SELECT json_agg(
            json_build_object(
                'id', i.id,
                'url', i.url,
                'alt', i.alt,
                'sort_order', i.sort_order
            )
            ORDER BY i.sort_order ASC, i.created_at ASC
        )
        FROM catalog.cabinet_images i
        WHERE i.cabinet_id = c.id
    ), '[]'::json)::jsonb AS images
FROM catalog.cabinets c
ORDER BY c.created_at DESC
`

type ListCabinetsRow struct {
	ID           string             `json:"id"`
	Slug         string             `json:"slug"`
	Model        string             `json:"model"`
	Type         string             `json:"type"`
	Display      string             `json:"display"`
	Condition    string             `json:"condition"`
	Quantity     int32              `json:"quantity"`
	Price        int64              `json:"price"`
	Manufacturer string             `json:"manufacturer"`
	Year         string             `json:"year"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Images       CabinetImages      `json:"images"`
}

func (q *Queries) ListCabinets(ctx context.Context) ([]ListCabinetsRow, error) {
	rows, err := q.db.Query(ctx, listCabinets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCabinetsRow
	for rows.Next() {
		var i ListCabinetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Model,
			&i.Type,
			&i.Display,
			&i.Condition,
			&i.Quantity,
			&i.Price,
			&i.Manufacturer,
			&i.Year,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Images,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
