// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CatalogCabinet struct {
	ID           string             `json:"id"`
	Slug         string             `json:"slug"`
	Model        string             `json:"model"`
	Type         string             `json:"type"`
	Display      string             `json:"display"`
	Condition    string             `json:"condition"`
	Quantity     int32              `json:"quantity"`
	Price        int64              `json:"price"`
	Manufacturer string             `json:"manufacturer"`
	Year         string             `json:"year"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type CatalogReservation struct {
	IdempotencyKey string             `json:"idempotency_key"`
	CabinetID      string             `json:"cabinet_id"`
	Quantity       int32              `json:"quantity"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
