// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CatalogCabinet struct {
	ID           string             `json:"id"`
	Slug         string             `json:"slug"`
	Model        string             `json:"model"`
	Type         string             `json:"type"`
	Display      string             `json:"display"`
	Condition    string             `json:"condition"`
	Quantity     int32              `json:"quantity"`
	Price        int64              `json:"price"`
	Manufacturer string             `json:"manufacturer"`
	Year         string             `json:"year"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type CatalogCabinetImage struct {
	ID        string             `json:"id"`
	CabinetID string             `json:"cabinet_id"`
	Url       string             `json:"url"`
	Alt       string             `json:"alt"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CatalogOrder struct {
	ID             string             `json:"id"`
	UserID         string             `json:"user_id"`
	Status         string             `json:"status"`
	TotalCents     int64              `json:"total_cents"`
	IdempotencyKey string             `json:"idempotency_key"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type CatalogOrderItem struct {
	ID             string `json:"id"`
	OrderID        string `json:"order_id"`
	CabinetID      string `json:"cabinet_id"`
	Quantity       int32  `json:"quantity"`
	UnitPriceCents int64  `json:"unit_price_cents"`
}

type CatalogOutbox struct {
	ID          interface{}        `json:"id"`
	AggregateID string             `json:"aggregate_id"`
	EventType   string             `json:"event_type"`
	Payload     []byte             `json:"payload"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

type CatalogReservation struct {
	IdempotencyKey string             `json:"idempotency_key"`
	CabinetID      string             `json:"cabinet_id"`
	Quantity       int32              `json:"quantity"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
