// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package db

import (
	"context"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO catalog.orders (id, user_id, status, total_cents, idempotency_key)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, status, total_cents, idempotency_key, created_at, updated_at
`

type CreateOrderParams struct {
	ID             string `json:"id"`
	UserID         string `json:"user_id"`
	Status         string `json:"status"`
	TotalCents     int64  `json:"total_cents"`
	IdempotencyKey string `json:"idempotency_key"`
}

// CreateOrder inserts a new order aggregate into the orders table.
func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (CatalogOrder, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.UserID,
		arg.Status,
		arg.TotalCents,
		arg.IdempotencyKey,
	)
	var i CatalogOrder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalCents,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :exec
INSERT INTO catalog.order_items (id, order_id, cabinet_id, quantity, unit_price_cents)
VALUES ($1, $2, $3, $4, $5)
`

type CreateOrderItemParams struct {
	ID             string `json:"id"`
	OrderID        string `json:"order_id"`
	CabinetID      string `json:"cabinet_id"`
	Quantity       int32  `json:"quantity"`
	UnitPriceCents int64  `json:"unit_price_cents"`
}

// CreateOrderItem inserts an individual item line belonging to an order.
func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error {
	_, err := q.db.Exec(ctx, createOrderItem,
		arg.ID,
		arg.OrderID,
		arg.CabinetID,
		arg.Quantity,
		arg.UnitPriceCents,
	)
	return err
}

const getOrder = `-- name: GetOrder :one
SELECT id, user_id, status, total_cents, idempotency_key, created_at, updated_at FROM catalog.orders WHERE id = $1 LIMIT 1
`

// GetOrder fetches a single order by its primary key ID.
func (q *Queries) GetOrder(ctx context.Context, id string) (CatalogOrder, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i CatalogOrder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalCents,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByItempotencyKey = `-- name: GetOrderByItempotencyKey :one
SELECT id, user_id, status, total_cents, idempotency_key, created_at, updated_at FROM catalog.orders WHERE idempotency_key = $1 LIMIT 1
`

// GetOrderByIdempotencyKey retrieves an existing order using its order idempotency key.
func (q *Queries) GetOrderByItempotencyKey(ctx context.Context, idempotencyKey string) (CatalogOrder, error) {
	row := q.db.QueryRow(ctx, getOrderByItempotencyKey, idempotencyKey)
	var i CatalogOrder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalCents,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO catalog.outbox (id, aggregate_id, event_type, payload)
VALUES ($1, $2, $3, $4)
`

type InsertOutboxEventParams struct {
	ID          interface{} `json:"id"`
	AggregateID string      `json:"aggregate_id"`
	EventType   string      `json:"event_type"`
	Payload     []byte      `json:"payload"`
}

// InsertOutboxEvent records an event in the outbox table within the active transaction.
func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent,
		arg.ID,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
	)
	return err
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT id, order_id, cabinet_id, quantity, unit_price_cents FROM catalog.order_items WHERE order_id = $1
`

// ListOrderItems fetches all item lines associated with a given order.
func (q *Queries) ListOrderItems(ctx context.Context, orderID string) ([]CatalogOrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CatalogOrderItem
	for rows.Next() {
		var i CatalogOrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.CabinetID,
			&i.Quantity,
			&i.UnitPriceCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnpublishedOutboxEvents = `-- name: ListUnpublishedOutboxEvents :many
SELECT id, aggregate_id, event_type, payload, created_at, published_at FROM catalog.outbox WHERE published_at IS NULL ORDER BY created_at ASC LIMIT $1
`

// ListUnpublishedOutboxEvents fetches pending outbox events for background worker dispatch.
func (q *Queries) ListUnpublishedOutboxEvents(ctx context.Context, limit int32) ([]CatalogOutbox, error) {
	rows, err := q.db.Query(ctx, listUnpublishedOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CatalogOutbox
	for rows.Next() {
		var i CatalogOutbox
		if err := rows.Scan(
			&i.ID,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventPublished = `-- name: MarkOutboxEventPublished :exec
UPDATE catalog.outbox SET published_at = NOW() WHERE id = $1
`

// MarkOutboxEventPublished marks an outbox event as successfilly sent.
func (q *Queries) MarkOutboxEventPublished(ctx context.Context, id interface{}) error {
	_, err := q.db.Exec(ctx, markOutboxEventPublished, id)
	return err
}
